### ISSUE TITLE
Bug: 좋아요/게시물저장/미니프로필/dm Room에 공통 500 에러 

### ISSUE THREAD

**Issue by kimyoungyin** [Instagram-Clone-Coding/Spring_instagram-clone#184]
저번주 배포 후 프론트 쪽에 올려주신 이슈가 전부 500번대 에러가 떠서 서버 쪽 문제일 것 같아 확인 한 번 부탁드립니다!
(400번대 에러는 이미 에러 처리는 다 해 두었는데 이런 식으로 공통적으로 에러가 뜨는거라..)
<img width="704" alt="스크린샷 2022-07-31 오후 10 40 55" src="https://user-images.githubusercontent.com/78777345/182029399-27607e5c-31ea-4cb0-91fc-633269bd7caa.png">
<img width="704" alt="스크린샷 2022-07-31 오후 10 41 16" src="https://user-images.githubusercontent.com/78777345/182029403-540eaf6f-f13c-4dbb-a120-14772cac2c72.png">
<img width="704" alt="스크린샷 2022-07-31 오후 10 41 27" src="https://user-images.githubusercontent.com/78777345/182029405-d60333d0-54b7-4b62-bc5a-f5609fe38161.png">
<img width="704" alt="스크린샷 2022-07-31 오후 10 41 44" src="https://user-images.githubusercontent.com/78777345/182029408-23080ac2-61b8-4a70-8d4f-d6a7c57aa60f.png">

## Describe the bug
✅ 버그를 재현하는 과정을 알려주세요.
1. 좋아요/좋아요 취소
2. 게시물 저장/저장 취소
3. 미니프로필 
4. dm room 리스트 불러오기

## To Reproduce
- 
서버 쪽 리팩토링 과정에서 놓친 게 있었는지 확인 부탁드립니다!

**Comment by vectorch9** [comment]
이전 배포에서 Post에 likeFlag가 추가됐는데, DB 초기화를 진행하지 않아 발생한 문제인 것 같습니다. 관련된 부분 초기화 시키겠습니다

**Comment by vectorch9** [comment]
> 이전 배포에서 Post에 likeFlag가 추가됐는데, DB 초기화를 진행하지 않아 발생한 문제인 것 같습니다. 관련된 부분 초기화 시키겠습니다

생각해보니 초기화 시킬 필요까진 없었네요.
DB에 쿼리 날려서 새로 추가된 column을 업데이트 해줬습니다. 현재 정상작동합니다!

**Comment by live-small** [comment]
지금 확인해보니까, 미니프로필, 좋아요/저장하기, 디엠목록도 잘 작동합니다
@kimyoungyin
