### ISSUE TITLE
비밀번호 재설정 페이지 url 에러 

### ISSUE THREAD

**Issue by live-small** [Instagram-Clone-Coding/Spring_instagram-clone#243]
## Describe the bug

<img width="1292" alt="스크린샷 2023-02-03 오후 5 40 40" src="https://user-images.githubusercontent.com/70274947/216553262-1ca59ae0-91c7-47bc-9bc5-e2421632ae58.png">
<img width="1428" alt="스크린샷 2023-02-03 오후 5 44 15" src="https://user-images.githubusercontent.com/70274947/216553300-1130938b-2d1d-4c21-80cc-44dba702129c.png">

- 비밀번호 재설정 메일에서 버튼 클릭 시, 해당 페이지 응답하는 시간이 너무 오래걸린다고 나옵니다! 
- **url을 봤을 때, 이전 배포서버로 연결되어있는 거 같은데 확인 부탁드릴게요** 
- 로그인 버튼 클릭시, 나오는 url  
    `http://ec2-3-36-185-121.ap-northeast-2.compute.amazonaws.com/accounts/login?username=suhwa&code=wUWHIP0BV4rgqPDGj15chVtN9aEbOC`
- 비밀번호 버튼 클릭 시, 나오는 url 
   `http://ec2-3-36-185-121.ap-northeast-2.compute.amazonaws.com/accounts/password/reset/confirm/?username=suhwa&code=wUWHIP0BV4rgqPDGj15chVtN9aEbOC`

## To Reproduce
- 

## Expected behavior
- 비밀번호 재설정 페이지가 나오도록!

**Comment by vectorch9** [comment]
@live-small 일단 버그 수정 커밋올려서 머지 후에 해결될 예정입니다. 다만 아직 프론트서버가 배포되지 않아서 정상동작하진 않습니다.
추가로, 이메일내 *메시지를 받은 이유에 대해 자세히 알아보세요* 부분을 누르면 실제 인스타그램의 링크로 이동되는데 이 부분은 의도하신걸까요?

**Comment by live-small** [comment]
>이메일내 메시지를 받은 이유에 대해 자세히 알아보세요 부분을 누르면 실제 인스타그램의 링크로 이동되는데 이 부분은 의도하신걸까요?

네네! 실제 인스타그램 메일과 동일하게 하기위해 해당 링크를 넣었는데! 수정하는 게 좋을까요? @bluetifulc

**Comment by vectorch9** [comment]
@live-small 저희 배포 페이지에 유사한 페이지를 만들어서 해당 링크를 넣으면 더 좋을거같아요 !
