### ISSUE TITLE
멤버 게시물 6개 조회 api에 불필요한 data도 response로 오는 문제

### ISSUE THREAD

**Issue by kimyoungyin** [Instagram-Clone-Coding/Spring_instagram-clone#247]
## 실제 인스타에 해당 데이터 사용 부분
<img width="987" alt="스크린샷 2023-02-08 오후 12 43 59" src="https://user-images.githubusercontent.com/78777345/217425870-01b0622b-357b-4756-8ded-8e9ed6b1d6a7.png">

## 요청 사항
- 게시물 단독 페이지에서 최근 게시물 6개의 요약 정보를 제공할 때 너무 많은 response를 얻어 수정 요청드립니다.

<img width="1080" alt="스크린샷 2023-02-08 오후 12 36 39" src="https://user-images.githubusercontent.com/78777345/217423970-fceb1264-d74a-4f89-8937-73d489a8878e.png">
<img width="405" alt="스크린샷 2023-02-08 오후 12 38 08" src="https://user-images.githubusercontent.com/78777345/217424342-c7bc1ce6-ddf7-49d4-84a4-967f59a12d15.png">

```ts
// 이 프로퍼티들만 제외하고 삭제하면 충분할 것 같습니다.
    interface PostType {
        postId: number;
        postImage: CommonType.PostImageDTOProps;
        hasManyPostImages: boolean;
        postCommentsCount: number;
        postLikesCount: number;
    }
```

**Comment by vectorch9** [comment]
@kimyoungyin 현재 해당 Response는 `MemberPostDto`로 작성되어있습니다. 말씀주신 사항을 살펴보니 다른 API에서도 해당 사항 외의 추가정보가 굳이 필요한가?라는 생각을 하게 되었습니다.

자세히 설명드리면, swagger상에서 **멤버 게시물 API** 하위의 API 대부분이 MemberPostDto를 사용합니다. 해당 API에서 member, likeOptionFlag, postLikeFlag도 반환하고 있는데 해당 정보가 프론트쪽에서 사용되고 있나요? 아마 없을 것 같은데 없는게 맞다면 전체적으로 수정하려합니다.

> member의 경우는 해당 멤버의 프로필에서 게시물을 조회하는 방식이라 중복되는 정보라 없어도 되지 않을까?라고 생각합니다. likeOptionFlag, postLikeFlag도 아마 게시물 세부정보 조회 페이지에서만 사용할거라고 예상됩니다

**Comment by kimyoungyin** [comment]
@bluetifulc 일단 간략한 정보만 나타내는 위와 같은 UI에서는 세부 설정에 대한 정보(좋아요 가능여부 등)는 필요하지 않습니다. 멤버 게시물 API에 속한 게 다 저 UI에 대응되는 API라면 수정하셔도 상관없을 것 같습니다!

혹시 postLikeFlag는 뭘까요? likeOptionFlag는 좋아요 및 조회수 표시 여부인 건 알겠습니다.

**Comment by vectorch9** [comment]
@kimyoungyin 아마 `postLikeFlag`가 게시물에 좋아요 눌렀는지 여부, `likeOptionFlag`는 게시물에 좋아요 가능 여부 일거에요.

그럼 멤버게시물관련 전체 API 응답에서 언급한 불필요한 정보는 제거하겠습니다.
